from drawmate.config import config

from drawmate.core.GCodeConverter import GCodeConverter
from drawmate.core.DrawMateStreamer import DrawMateStreamer
from pathlib import Path
import sys

config = config.get_config()

AI_ENABLED = True
if AI_ENABLED:
    from drawmate.ai.LineArtGenerator import LineArtGenerator
    from google.genai import errors


def main():
    # Handle input image
    if len(sys.argv) > 1:
        INPUT_IMAGE = Path(sys.argv[1])
        if not INPUT_IMAGE.exists():
            print(f"[!] Image file not found: {INPUT_IMAGE}")
            return
        print(f"🖼️ Using input image: {INPUT_IMAGE}")
    else:
        INPUT_IMAGE = config.ASSET_DIR / "snowflake.png"
        print(f"🖼️ No image argument provided. Using default: {INPUT_IMAGE}")

    # --- Conversion pipeline ---
    gcode_converter = GCodeConverter(
        config.DATA_ASSET_DIR,
        config.GCODE_DIR,
        config.CANVAS_WIDTH_IN_MILLIMETERS,
        config.CANVAS_HEIGHT_IN_MILLIMETERS
    )

    # Immediately send the user image to LineArtGenerator and draw AI image
    # --- AI Line Art Generation ---
    if AI_ENABLED:
        ai_output_path = None
        try:
            line_art_generator = LineArtGenerator()
            ai_output_path = line_art_generator.generate(
                INPUT_IMAGE,
                config.DEFAULT_PROMPT
            )

            if ai_output_path:
                print(f"Line art generated: {ai_output_path}")
            else:
                print("No image generated by AI.")
        except errors.APIError as e:
            print(f"API Error: {e.code}: {e.message}")
        except FileNotFoundError as e:
            print(e)
    else:
        print("🤖 AI features disabled. Skipping line-art generation.")
        return

    print("🖼️  Step 1: Converting raster to SVG...")
    svg_file_path = gcode_converter.raster_to_svg(ai_output_path if ai_output_path else INPUT_IMAGE)

    print("⚙️  Step 2: Converting SVG to G-code...")
    gcode_path = gcode_converter.svg_to_gcode(svg_file_path)

    print(f"✅ G-code file created: {gcode_path}")

    # --- Stream to DrawMate ---
    print("📡 Step 3: Streaming G-code to DrawMate...")
    streamer = DrawMateStreamer()
    streamer.stream_gcode(gcode_path)

    print("🎉 Done! The DrawMate should now be plotting.")


if __name__ == "__main__":
    main()
